### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by telegraphic**
As suggested at the CASPER 2018 meeting, we should have a code of conduct. This one is based on the 'Citizen code of Conduct', and is more appropriate than the other Github templated 'Convenant code of conduct' as it covers meetings. Could also consider basing on http://www.astropy.org/code_of_conduct.html

### CODE REVIEW

**Comment by jack-h** [comment]
Thanks Adam. (And thanks Danny for adding). Can you leave this out for now,
we are currently having a conversation about this in the advisory board.

**Comment by bjbford** [comment]
@jack-h when its ready I can add it into readthedocs as @AdamI75 suggested. Will talk more at the developer telecon next month...

**Comment by telegraphic** [comment]
Yes, advisory board blessing is the way to go. I nonetheless suggest keeping the pull request open as a reference data point from github community standards, and also so it doesn't slip through the cracks.

**Comment by AdamI75** [comment]
I agree with Danny that we keep this on the pull request and publish it officially later when the board is happy for this to be done.

**Comment by jack-h** [comment]
Accepted this code into local branch `code-of-conduct`. PR #79 for this branch pending.
Closing this PR.
Thanks @telegraphic

**Pull request closed without merging**
