### PR TITLE
 Updating the snap platform to support scratchpad default value a8776f4 

### PR DESCRIPTION
**Pull request by mchirindo**
@jack-h    Can you please review and merge with casper-astro/mlib_devel

Mathews

### CODE REVIEW

**Comment by jack-h** [comment]
It looks like this is trying to fix the fact that commit 71aeffbe28 changed the API requirements to instantiate a sys_block, which isn't accounted for by SNAP(?)
I don't know why this was changed, but a quick grep at the various other yellow blocks suggests to me that *every* platform has been broken.
Can you modify them all, please? Or revert the change from 71aeffbe28 which broke everything? (Or if everything is fine and I'm mistaken tell me to be quiet).

**Comment by AdamI75** [comment]
Jack, you are correct. Mathews has updated the sys_block API which includes
defaults for scratchpad register and AXI updates. We compiled on SKARAB,
Red Pitaya, Alveo and SNAP. What other platforms would be broken with this
change? SNAP2 and ZCU111?

@Mathews: I suggest you delete this pull request and we update the other
<platform>.py files under the "yellow_blocks" folder. Then redo the pull
request. This would be the easiest, thanks.

**Comment by jack-h** [comment]
`grep sys_block $MLIB_DEVEL_PATH/jasper_library/yellow_blocks`

suggests that the current mlib_devel master branch instantiates `sys_block`'s without scratchpads defined in:
`casia_k7_21cma.py`
`casia_k7.py`
`mx175.py`
`skarab.py`
`snap2.py`
`snap2_v2.py`
`snap.py`
`vcu118.py`
`vcu128.py`
`zcu111.py`

This commit seems to fix only SKARAB and SNAP1

**Comment by AdamI75** [comment]
Thanks, we will fix this issue shortly. My mistake and not Mathews. I had
forgotten we had merged all the different platforms last year. I think the
Red Pitaya was already updated.

**Comment by jack-h** [comment]
PR #125 should make the fixes we talked about obsolete, by re-supporting the original block construction API. Probably easier than changing every use of sys_block in the repo.

**Comment by AdamI75** [comment]
@mchirindo : please make the changes as @jack-h suggests, thanks.

**Comment by jkocz** [comment]
Closing this as the current ska-sa devel branch will be merged as part of the 2020 busy week.

**Pull request closed without merging**
