### PR TITLE
commented out simulation value munging that seems to break simulation

### PR DESCRIPTION
**Pull request by moragb96**

### CODE REVIEW

**Comment by jack-h** [comment]
Can you note the test / test parameters which were broken and now are not?

**Comment by moragb96** [comment]
Below sinusoid loaded as shared_bram simulation values:

Screenshot from 2022-10-28 14-30-56

**With this change not included in the mask script**

For data width 32:
Screenshot from 2022-10-28 14-26-16

For data width 64:
Screenshot from 2022-10-28 14-26-46

**With this change still in the mask script**

For data width 32: 
Screenshot from 2022-10-28 14-27-23

For data width 64:
Screenshot from 2022-10-28 14-28-19

At some point I managed to get a sane output for 32 bit data for address width >= 10, but that seems to only have been for that one very specific dataset I was using at the time. And I have no idea why the address width would make a difference there.

**Comment by jack-h** [comment]
Thanks. Without the bit mashing, does the simulation also work when writing
values into the ram then reading them out?

**Comment by moragb96** [comment]
> Without the bit mashing, does the simulation also work when writing
values into the ram then reading them out?

Testing this has now uncovered that writing values into the bram doesn't simulate at all. Should we hold off on this PR until someone (which I guess is me) has figured that out, or can we fix the original issue in the meantime?

**Comment by jack-h** [comment]
My suspicion is that fixing the issue here will break (on top of what seems
already broken) the relationship between written and read bits.
Fundamentally there seems to be a disagreement about where the firmware
data mungers are, and whether the simulation data includes or excludes
these (and thus whether or not it should include its own munge)

**Comment by moragb96** [comment]
Just dropping in to say I haven't forgotten about this, work and studies are just [waves hands frantically]. I don't see anything obviously wrong with the sfunc for the block that would be the reason stuff on data in doesn't propagate - but if you had this fix in to munge simulation data, it must have worked at some point??

**Pull request closed without merging**
