### PR TITLE
Remove MATLAB-based toolflow stuff

### PR DESCRIPTION
**Pull request by jack-h**
- yellow block MATLAB classes
- xps_base packages
- casper_xps function and GUI

### CODE REVIEW

**Comment by jack-h** [comment]
Does this seem like a good idea?

**Comment by AdamI75** [comment]
If it is not being used then it is a good idea to remove it. I had a brief look through all the files and they look obsolete to me, so I say go ahead.

**Comment by jack-h** [comment]
Access looks fine to me....

**Comment by AdamI75** [comment]
I was being silly. I have approved it.

**Comment by jack-h** [comment]
Removed: 1.3M lines of code. Hard not to be happy about that!

**Comment by AdamI75** [comment]
Very sad for the developer though. However, if one of those lines is needed in the new toolflow then it WILL be very sad for us :(

**Pull request merged**
