### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by moragb96**
- Changed MATLAB to Matlab (there was an annoying thing where the docs sometimes had it as MATLAB and other times as Matlab. I made the stylistic decision to choose Matlab so the docs are less... screamy)
- Reworked Running the Toolflow to be clearer and neater

### CODE REVIEW

**Review by jkocz — APPROVED** [review]

**Comment by kiranshila** [comment]
I'm unsure if I agree with this change - the product is called MATLAB, not Matlab. It's [an abbreviation for Matrix Laboratory](https://www.mathworks.com/help/matlab/learn_matlab/matrices-and-arrays.html)

**Comment by moragb96** [comment]
> I'm unsure if I agree with this change - the product is called MATLAB, not Matlab. It's [an abbreviation for Matrix Laboratory](https://www.mathworks.com/help/matlab/learn_matlab/matrices-and-arrays.html)

@kiranshila Yeah, I've been thinking about changing it back to MATLAB cos it bothers me too. The issue was that half the docs referred to it as Matlab, and the other half as MATLAB, and sometimes it would vary throughout a single doc. I thought maybe not having it as all caps would help with readability, especially in the installation instructions where MATLAB is mentioned a lot - but I don't think it really makes a difference.

**Comment by jack-h** [comment]
For what little my vote is worth, I think MATLAB is better (since as Kiran
points out, it is more "correct")

**Comment by moragb96** [comment]
Okidoki, will do a good ol' :%s/Matlab/MATLAB when I have a mo this weekend

**Pull request merged**
