### PR TITLE
Fixed Sphinx documentation warnings for all docstrings.

### PR DESCRIPTION
**Pull request by bjbford**

### CODE REVIEW

**Comment by AdamI75** [comment]
Hi @bjbford, we are no longer using branch casper-astro-soak-test-ska.  I suggest you add these changes to casper-astro-soak-test branch only. We can delete the casper-astro-soak-test branch to avoid confusion. Please rectify, thanks.

**Comment by bjbford** [comment]
Hi @AdamI75 I have been committing documentation updates to casper-astro-soak-test-ska since busyweek as this is the branch that readthedocs is currently building from. My plan was to merge this branch back into casper-astro-soak-test once the docs are stable are ready for release. I also did not want to litter casper-astro-soak-test with all of these minor commits.

That being said I could make a proper 'documentation' branch or commit directly to casper-astro-soak-test if you prefer? No worries, thanks.

P.S. the docs are now in a stable state... Just some minor tweaks that bug me.

**Comment by AdamI75** [comment]
Hi @bjbford, I think committing to casper-astro-soak-test would be the best option, but first check with Jack about this or whether he wants to create a new branch. Thank you!

**Comment by jack-h** [comment]
If you can get everything in the main soak-test branch as sokn as vaguely
stable that'd be good. If you want further changes then maybe make a new
docs branch. I think it would be good to retire the soak-test-ska branch,
which was (supposed to be) all about fixing casper-astro/ska conflicts.

In any case, thanks for the improvements!

**Comment by bjbford** [comment]
@jack-h understandable, will do!

**Comment by jack-h** [comment]
Thanks. I've made another PR to put these in the soak-test branch. When
that's approved I'll delete the ska one.

**Pull request merged**
