### PR TITLE
Casper astro soak test ska

### PR DESCRIPTION
**Pull request by jack-h**
This merge pulls in development from the ska-sa devel branch.

It has been tested to the extent that skarab tutorials successfully update with `update_casper_blocks(bdroot)` and pass an `update diagram`

### CODE REVIEW

**Comment by AdamI75** [comment]
Jack, David and Brian: thanks for fixing the bitfield_snapshot block and I agree with David. Yes, the issue with the forty_gbe yellow block was to do with the dvalid and the unsigned issue, as pointed out. I have generated new slx files, which fix this issue. The dvalid change is a valid change, as previously it was a assumed a 4 bit signal. The CBF guys wanted it to be a 1 bit signal, so the yellow block was updated. I suspect the tx_data was a similar issue. This is fixed now, so I am happy. Once the final merge occurs next week then I will retest the SKARAB tutorials with the CASPER 2018 merge version.

**Comment by jack-h** [comment]
Thanks Adam, I'll look in to these.

**Comment by jack-h** [comment]
All happy to finally let this through?

**Comment by AdamI75** [comment]
I am happy that you merge when ready to do so.

**Pull request merged**
