### PR TITLE
M2021a

### PR DESCRIPTION
**Pull request by amartens**
Repo cleanup. Unused script removal

### CODE REVIEW

**Comment by jkocz** [comment]
Looks like I forgot about this, and now we have the problem of extra commits on the branch. - I think the best thing would be to either take just the original commits from @amartens, and make other changes to a dev branch, or move the entire pull request to a dev branch of m2021a.

**Comment by jack-h** [comment]
What's the status with this? From the looks of these commits they all seem both good (I'll tolerate the differing opinions about `DUMB_BRAMS` :) ) and non-conflicting

**Comment by jkocz** [comment]
In theory I'm in favor of merging... but it was only the first 4 commits before the merge back into ska-sa that were the pull request. Everything since then has been e.g. since ska-sa needed async ffts. I would much prefer to merge this to a new dev/soak branch (say m2021a-dev).

With the FFT, would it be good also to make `DUMB_BRAMS` a setting option rather than requiring a code change? This was done originally to improve timing? Would it be worth checking the impact on timing of changing it back?

**Comment by jack-h** [comment]
On Wed, 23 Nov 2022 at 16:07, J. Kocz ***@***.***> wrote:

> In theory I'm in favor of merging... but it was only the first 4 commits
> before the merge back into ska-sa that were the pull request. Everything
> since then has been e.g. since ska-sa needed async ffts. I would much
> prefer to merge this to a new dev/soak branch (say m2021a-dev).
>
> With the FFT, would it be good also to make DUMB_BRAMS a setting option
> rather than requiring a code change? This was done originally to improve
> timing? Would it be worth checking the impact on timing of changing it back?
>
I added the option to save lots of logic and power for the LWA. It could be
a block setting, but that would require playing the game of propagating the
parameter all the way up through the blocks rather than than just tweaking
some .m files

**Comment by jkocz** [comment]
> I added the option to save lots of logic and power 

That seems like a good argument for going through the pain of making it a block setting. I'm happy to take that on, but I think would rather leave it as not merging to the main branch until then. I'll create a m2021a-dev - @amartens could you switch the pull request to be to that branch instead?

**Comment by amartens** [comment]
Yeah, this is a bit of a mix now. 

@jkocz I am happy doing a pull request to a different branch so that we can keep things separate until people are happy.

@jack-h I have left the DUMB_BRAMS code, just changed the default. I have tweaked the logic so that if you have a high max fanout setting the amount of fanout logic can go down to none i.e the same as the DUMB_BRAMS setting. So you should be able to get the same saving without giving up the ability to have an asynchronous FFT (or modifying the mask). You could just turn DUMB_BRAMS back on though if it isn't to your satisfaction.

The symmetric PFB FIR coefficient fix removes a bunch of logic so should also help timing, power etc (and be correct). 

Should we close this pull request and try again?

**Pull request merged**
